  name: Android Build
  on: pull_request

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: setup_jdk
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Run_test
          run: ./gradlew test